
package service;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "NoSuchProductException", targetNamespace = "http://webservices.sud/")
public class NoSuchProductException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoSuchProductException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoSuchProductException_Exception(String message, NoSuchProductException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public NoSuchProductException_Exception(String message, NoSuchProductException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: sud.webservices.NoSuchProductException
     */
    public NoSuchProductException getFaultInfo() {
        return faultInfo;
    }

}
